# Generated by Django 5.2.6 on 2025-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
    ]
